"""Qlik→ThoughtSpot formula mapping reference (sub-utility).

Loads the canonical 199-row mapping table (q2t/data/qlik_ts_formula_map.json,
generated by build_formula_map.py from the verified CSV) and provides:

  * lookup(text)   -> mapping rows matching a Qlik function name or substring
  * classify(expr) -> for a single Qlik expression, the functions it uses and
                      whether each is translatable / manual / verify
  * audit(exprs)   -> coverage summary across many expressions

This is the *reference/coverage* layer. expr.py remains the actual translator;
this tells you, before translating, how much of an app's formula surface will
convert cleanly vs. need manual work — the "audit mode" of the migration.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from functools import lru_cache
from typing import Any, Optional

_DATA = os.path.join(os.path.dirname(__file__), "..", "data", "qlik_ts_formula_map.json")

# Markers in the ThoughtSpot column that mean "no clean equivalent".
_MANUAL_MARKERS = ("no direct equivalent", "no equivalent")
_FUNC_TOKEN = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(")


@dataclass
class Mapping:
    id: str
    category: str
    qlik: str
    qlik_example: str
    ts: str
    ts_example: str
    comment: str
    status: str            # ok | corrected | verify

    @property
    def tier(self) -> str:
        if self.status == "verify":
            return "verify"
        if any(m in self.ts.lower() for m in _MANUAL_MARKERS):
            return "manual"
        return "translatable"


@lru_cache(maxsize=1)
def _rows() -> list[Mapping]:
    with open(_DATA, encoding="utf-8") as fh:
        raw = json.load(fh)
    out = []
    for r in raw:
        out.append(Mapping(
            id=r.get("#", ""), category=r.get("Category", ""),
            qlik=r.get("Qlik Sense Formula", ""), qlik_example=r.get("Qlik Example", ""),
            ts=r.get("ThoughtSpot Equivalent", ""), ts_example=r.get("ThoughtSpot Example", ""),
            comment=r.get("Comments / Context", ""), status=r.get("status", "ok"),
        ))
    return out


@lru_cache(maxsize=1)
def _by_fn() -> dict[str, list[Mapping]]:
    """Index by the leading Qlik function/operator token (lowercased)."""
    idx: dict[str, list[Mapping]] = {}
    for m in _rows():
        token = re.match(r"\s*([A-Za-z_][A-Za-z0-9_]*)", m.qlik)
        if token:
            idx.setdefault(token.group(1).lower(), []).append(m)
    return idx


# -- public API ------------------------------------------------------------

def lookup(text: str) -> list[Mapping]:
    """Find mappings by Qlik function name or free-text substring."""
    text = text.strip().lower()
    hits = list(_by_fn().get(text, []))
    if hits:
        return hits
    return [m for m in _rows()
            if text in m.qlik.lower() or text in m.ts.lower() or text in m.category.lower()]


def classify(expr: str) -> list[tuple[str, Optional[Mapping]]]:
    """Return (function_name, mapping-or-None) for each function used in expr."""
    seen, result = set(), []
    for fn in _FUNC_TOKEN.findall(expr or ""):
        low = fn.lower()
        if low in seen:
            continue
        seen.add(low)
        rows = _by_fn().get(low)
        result.append((fn, rows[0] if rows else None))
    return result


def audit(expressions: list[str]) -> dict[str, Any]:
    """Coverage summary across a list of Qlik expressions."""
    translatable, manual, verify, unknown = set(), set(), set(), set()
    for expr in expressions:
        for fn, m in classify(expr):
            if m is None:
                unknown.add(fn)
            elif m.tier == "manual":
                manual.add(fn)
            elif m.tier == "verify":
                verify.add(fn)
            else:
                translatable.add(fn)
    total = len(translatable | manual | verify | unknown)
    return {
        "expressions": len(expressions),
        "distinct_functions": total,
        "translatable": sorted(translatable),
        "manual": sorted(manual),
        "verify": sorted(verify),
        "unknown": sorted(unknown),
        "coverage_pct": round(100 * len(translatable) / total, 1) if total else 100.0,
    }


def stats() -> dict[str, int]:
    """Overall table stats (rows by status/tier)."""
    rows = _rows()
    by_status: dict[str, int] = {}
    by_tier: dict[str, int] = {}
    for m in rows:
        by_status[m.status] = by_status.get(m.status, 0) + 1
        by_tier[m.tier] = by_tier.get(m.tier, 0) + 1
    return {"rows": len(rows), **{f"status_{k}": v for k, v in by_status.items()},
            **{f"tier_{k}": v for k, v in by_tier.items()}}
