version: 2
updates:
  - package-ecosystem: pip
    directory: /tools/q2t-cli
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /qvf-engine-extract
    schedule:
      interval: weekly
