"""Build TML for the Retail Analytics demo over DB_CASESTUDY.QLIKMIG_DEMO.
2 facts (FACT_SALES, FACT_RETURNS) + 6 conformed dims. Reuses connection
QlikMig_CaseStudy_SF. Generated by the ts-convert-from-qlik (no-API) flow."""
import os, yaml
CONN="QlikMig_CaseStudy_SF"; DB="DB_CASESTUDY"; SCHEMA="QLIKMIG_DEMO"
PFX="QM_"; MODEL="QlikMig Retail Analytics"; OUT="build/demo_tml"
os.makedirs(OUT, exist_ok=True)
I,D,V="INT64","DOUBLE","VARCHAR"
def col(n,t,ct="ATTRIBUTE",agg=None):
    p={"column_type":ct}
    if agg:p["aggregation"]=agg
    return {"name":n,"db_column_name":n,"properties":p,"db_column_properties":{"data_type":t}}
TABLES={
 "DIM_DATE":[col("DATE_KEY",I),col("FULL_DATE","DATE"),col("DAY",I),col("MONTH",I),
   col("MONTH_NAME",V),col("QUARTER",V),col("YEAR",I),col("WEEK_OF_YEAR",I),col("IS_WEEKEND","BOOL")],
 "DIM_CUSTOMER":[col("CUSTOMER_KEY",I),col("CUSTOMER_ID",V),col("FIRST_NAME",V),col("LAST_NAME",V),
   col("GENDER",V),col("SEGMENT",V),col("REGION",V),col("COUNTRY",V)],
 "DIM_PRODUCT":[col("PRODUCT_KEY",I),col("PRODUCT_ID",V),col("PRODUCT_NAME",V),col("CATEGORY",V),
   col("SUBCATEGORY",V),col("BRAND",V),col("LIST_PRICE",I),col("UNIT_COST",D)],
 "DIM_STORE":[col("STORE_KEY",I),col("STORE_ID",V),col("STORE_NAME",V),col("STORE_TYPE",V),
   col("REGION",V),col("COUNTRY",V)],
 "DIM_CHANNEL":[col("CHANNEL_KEY",I),col("CHANNEL_NAME",V)],
 "DIM_PROMOTION":[col("PROMO_KEY",I),col("PROMO_NAME",V),col("PROMO_TYPE",V),col("DISCOUNT_PCT",I)],
 "FACT_SALES":[col("SALES_KEY",I),col("DATE_KEY",I),col("CUSTOMER_KEY",I),col("PRODUCT_KEY",I),
   col("STORE_KEY",I),col("CHANNEL_KEY",I),col("PROMO_KEY",I),col("ORDER_NUMBER",V),
   col("QUANTITY",I,"MEASURE","SUM"),col("UNIT_PRICE",I),col("DISCOUNT_AMOUNT",D),
   col("SALES_AMOUNT",D,"MEASURE","SUM"),col("COST_AMOUNT",D),col("PROFIT_AMOUNT",D,"MEASURE","SUM")],
 "FACT_RETURNS":[col("RETURN_KEY",I),col("DATE_KEY",I),col("CUSTOMER_KEY",I),col("PRODUCT_KEY",I),
   col("STORE_KEY",I),col("RETURN_NUMBER",V),col("QUANTITY_RETURNED",I,"MEASURE","SUM"),
   col("REFUND_AMOUNT",I,"MEASURE","SUM"),col("REASON",V)],
}
def dump(doc,f):
    with open(os.path.join(OUT,f),"w") as fh: yaml.safe_dump(doc,fh,sort_keys=False,default_flow_style=False)
for t,cols in TABLES.items():
    dump({"table":{"name":PFX+t,"db":DB,"schema":SCHEMA,"db_table":t,"connection":{"name":CONN},"columns":cols}},f"table.{PFX}{t}.tml")
def j(fact,dim,key):
    return {"with":PFX+dim,"on":f"[{PFX}{fact}::{key}] = [{PFX}{dim}::{key}]","type":"INNER","cardinality":"MANY_TO_ONE"}
model={"name":MODEL,"description":"Migrated from Qlik 'Retail Analytics' (no-API path). Source: DB_CASESTUDY.QLIKMIG_DEMO.",
 "model_tables":[
   {"name":PFX+"FACT_SALES","joins":[j("FACT_SALES","DIM_DATE","DATE_KEY"),j("FACT_SALES","DIM_CUSTOMER","CUSTOMER_KEY"),
      j("FACT_SALES","DIM_PRODUCT","PRODUCT_KEY"),j("FACT_SALES","DIM_STORE","STORE_KEY"),
      j("FACT_SALES","DIM_CHANNEL","CHANNEL_KEY"),j("FACT_SALES","DIM_PROMOTION","PROMO_KEY")]},
   {"name":PFX+"FACT_RETURNS","joins":[j("FACT_RETURNS","DIM_DATE","DATE_KEY"),j("FACT_RETURNS","DIM_CUSTOMER","CUSTOMER_KEY"),
      j("FACT_RETURNS","DIM_PRODUCT","PRODUCT_KEY"),j("FACT_RETURNS","DIM_STORE","STORE_KEY")]},
   {"name":PFX+"DIM_DATE"},{"name":PFX+"DIM_CUSTOMER"},{"name":PFX+"DIM_PRODUCT"},
   {"name":PFX+"DIM_STORE"},{"name":PFX+"DIM_CHANNEL"},{"name":PFX+"DIM_PROMOTION"},
 ],
 "formulas":[{"id":"f_margin","name":"Profit Margin","expr":f"(sum([{PFX}FACT_SALES::PROFIT_AMOUNT]) / sum([{PFX}FACT_SALES::SALES_AMOUNT])) * 100"}],
 "columns":[
   {"name":"Category","column_id":f"{PFX}DIM_PRODUCT::CATEGORY","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Subcategory","column_id":f"{PFX}DIM_PRODUCT::SUBCATEGORY","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Brand","column_id":f"{PFX}DIM_PRODUCT::BRAND","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Product Name","column_id":f"{PFX}DIM_PRODUCT::PRODUCT_NAME","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Region","column_id":f"{PFX}DIM_STORE::REGION","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Country","column_id":f"{PFX}DIM_STORE::COUNTRY","properties":{"column_type":"ATTRIBUTE","geo_config":{"country":True}}},
   {"name":"Store Type","column_id":f"{PFX}DIM_STORE::STORE_TYPE","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Channel","column_id":f"{PFX}DIM_CHANNEL::CHANNEL_NAME","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Segment","column_id":f"{PFX}DIM_CUSTOMER::SEGMENT","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Year","column_id":f"{PFX}DIM_DATE::YEAR","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Month Name","column_id":f"{PFX}DIM_DATE::MONTH_NAME","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Quarter","column_id":f"{PFX}DIM_DATE::QUARTER","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Date","column_id":f"{PFX}DIM_DATE::FULL_DATE","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Return Reason","column_id":f"{PFX}FACT_RETURNS::REASON","properties":{"column_type":"ATTRIBUTE"}},
   {"name":"Sales","column_id":f"{PFX}FACT_SALES::SALES_AMOUNT","properties":{"column_type":"MEASURE","aggregation":"SUM"}},
   {"name":"Profit","column_id":f"{PFX}FACT_SALES::PROFIT_AMOUNT","properties":{"column_type":"MEASURE","aggregation":"SUM"}},
   {"name":"Units Sold","column_id":f"{PFX}FACT_SALES::QUANTITY","properties":{"column_type":"MEASURE","aggregation":"SUM"}},
   {"name":"Refunds","column_id":f"{PFX}FACT_RETURNS::REFUND_AMOUNT","properties":{"column_type":"MEASURE","aggregation":"SUM"}},
   {"name":"Units Returned","column_id":f"{PFX}FACT_RETURNS::QUANTITY_RETURNED","properties":{"column_type":"MEASURE","aggregation":"SUM"}},
   {"name":"Profit Margin","formula_id":"f_margin","properties":{"column_type":"MEASURE"}},
 ],
}
dump({"model":model},f"model.{PFX}model.tml")
print("wrote",len(os.listdir(OUT)),"TML files (8 tables + model)")
